name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    env:
      HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check if HuggingFace token is set
      run: |
        if [ -z "$HUGGINGFACE_TOKEN" ]; then
          echo "Token not set"
          exit 1
        else
          echo "Token is set"
        fi

    - name: Run backend tests
      run: pytest tests

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: test-backend
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/chatbot:latest
        IMAGE_NAME_LOWER=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')
        docker build -t $IMAGE_NAME_LOWER .
        docker push $IMAGE_NAME_LOWER


  deploy-to-azure:
    runs-on: ubuntu-latest
    needs: build-and-push-image

    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: chatbot-appservice
        images: ghcr.io/${{ github.repository_owner }}/chatbot:latest



