name: Build and Deploy to Azure

on:
  push:
    branches:
      - master  # o main si es tu rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login chatbotearc.azurecr.io -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Build and push Docker image to ACR
        run: |
          docker build -t chatbotearc.azurecr.io/chatbot:latest .
          docker push chatbotearc.azurecr.io/chatbot:latest

      - name: Deploy to Azure Web App (Container)
        uses: azure/webapps-deploy@v2
        with:
          app-name: chatbot-flask-app  # ⚠️ Cambia esto si tu Web App se llama diferente
          slot-name: production
          images: chatbotearc.azurecr.io/chatbot:latest

